### ISSUE TITLE
correlationid not logged with NLOG

### ISSUE THREAD

**Issue by erikbullens** [skwasjer/Correlate#6]
Hi,
I try to log the correlationID in my logging but there's only an empty column.
I followed the instructions and tried several options but no luck.
Can anyone see the problem?

[correlationExample.zip](https://github.com/skwasjer/Correlate/files/3932834/correlationExample.zip)
[correlationExample.zip](https://github.com/skwasjer/Correlate/files/3932836/correlationExample.zip)

**Comment by skwasjer** [comment]
Try `${mdlc:CorrelationId}`
