### ISSUE TITLE
Using Hangfire.Correlate, after registering everything, I get numerical CorrelationId

### ISSUE THREAD

**Issue by mterwoord** [skwasjer/Correlate#8]
Documentation says default should be to use guids, but that doesn't work.

Manually doing `services.AddSingleton<ICorrelationIdFactory, GuidCorrelationIdFactory>();` doesn't help. First doing `RemoveAll<ICorrelactionIdFactory>();` neither. 

Am I missing something?

**Comment by skwasjer** [comment]
The hangfire integration works slightly different:

> Job execution
> When the job is 'performed' (in Hangfire terms), the job parameter (for correlation id) that was added during job creation will be used to create a new correlation context, thus reviving the correlation context. This means that even in distributed scenarios, the same correlation id is used to process the job.
> 
> If no correlation id was stored with the job, yet also to remain backwards compatible with existing jobs (prior to Correlate integration), the job id will be used instead.

https://github.com/skwasjer/Hangfire.Correlate#job-execution

If you enqueue a job outside an ASP.NET context the job ID is used and the `ICorrelationIdFactory` is ignored. This is to ensure jobs - that were scheduled before Correlate integration was added - still work.

If you really want to have guids, you could create a new correlation context and queue the job inside of that:

```csharp
await _correlationManager.CorrelateAsync(async () =>
{
    // Queue job here.
}
```
In this scenario, the `ICorrelationIdFactory` factory will be used (but still only for newly queued jobs).

**Comment by mterwoord** [comment]
ok, thanks. Sorry for not reading that part well enough. I'll close this issue now.
